### ISSUE TITLE
Allow optional fields?

### ISSUE THREAD

**Issue by marnickmenting** [IntVent/eboekhouden-php#6]
I don't see a possibility to leave fields out when creating objects. For example Factuur->Betalingstermijn is optional in the API. This means e-boekhouden will fill the value from debtor information I assume. Right now I am obligated to send a payment_term, which I don't know because it is not retrievable from the Relations API...

**Comment by petericebear** [comment]
I will look into this one, can be made optional of course if the API supports it.

**Comment by marnickmenting** [comment]
It is basically an obligation at 2 steps now. In the constructs you have to provide all fields in the $item array. AND it will send all values to the API endpoint. Both should be optional.

I see it is quite a rewrite to do that. I need it only for the payment term, will try to do that in a fork.

**Comment by marnickmenting** [comment]
It turns out the payment term is a required field in the API. So I will close this issue as this is not relevant to me anymore.
