### ISSUE TITLE
Typo in Client->getSaldo function

### ISSUE THREAD

**Issue by vanrooij-it** [IntVent/eboekhouden-php#9]
Hi,

I noticed there's a typo in the getSaldo function in the Client class on line 353

'DatumTm' => $dateTo->format('Y-m-d'),

should be:

'**DatumTot**' => $dateTo->format('Y-m-d'),

regards,

Marco

**Comment by petericebear** [comment]
Hi Marco,
Thanks, I updated the line and will tag a new minor version for the Client.
